apiVersion: apps/v1

kind: Deployment

metadata:
  name: Postgres-sql
  namespace: default

spec:
  replicas: 3
  selector:
    matchLabels: postgres
  
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim

      containers:
      - name: postgres
        image: postgres:12-alpine   
        ports:
          - containerPort: 5432
        
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        
        env:
        
